server:
  port: 9011
spring:
  application:
    name: activemq-producer
#springboot与activemq整合
  activemq:
    broker-url: tcp://192.168.177.128:61616
    user: admin
    password: admin
#指定发送模式（点对点false(默认)，发布订阅true）
  jms:
    pub-sub-domain: false