#多环境的演示
#server:
#  port: 8083
#spring:
#  profiles:
#    active: dev
#---
#server:
#     port: 8081
#spring:
#  profiles: dev
#---
#server:
#  port: 8082
#spring:
#  profiles: prd


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?t_user=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      #最大连接池数量
      max-active: 200
      #初始化时建立物理连接的个数
      initial-size: 10
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #最小连接池数量
      min-idle: 10
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      #validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #是否缓存preparedStatement
      pool-prepared-statements: true
      #要启用PSCache，必须配置大于0
      max-open-prepared-statements: 200
      break-after-acquire-failure: true
      time-between-connect-error-millis: 300000
  jpa:
    show-sql: true
  mail:
    host: smtp.163.com
    port:
    username: wwpang@163.com
    password: XCRYNKLCLYKLTGPW
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

#mybatis-plus全局配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto  #主机自增策略


server:
  port: 7777
#cas:
#  server-url-prefix: http://localhost:9080/cas #cas服务端的地址
#  server-login-url: http://localhost:9080/cas/login #cas没通过认证后的跳转地址
#  client-host-url: http://test.com:7777 #客户端访问地址
#  validation-type: cas3
