server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/penguin?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    cn.pww.mapper: debug
